package io.github.ladium1.erp.global.demo;

import io.github.ladium1.erp.global.exception.BusinessException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.transaction.support.TransactionTemplate;

import java.io.IOException;
import java.nio.file.Path;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.UUID;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class DemoUploadQuotaGuardTest {

    private static final LocalDateTime RESET_AT = LocalDateTime.of(2026, 8, 13, 9, 0);
    private static final Path STORAGE_PATH = Path.of("/demo/files/current");

    private DemoProperties properties;
    private JdbcTemplate jdbcTemplate;
    private TransactionTemplate transactionTemplate;

    @BeforeEach
    void setUp() {
        properties = new DemoProperties();
        properties.setEnabled(true);
        properties.getUpload().setAccountQuotaBytes(10);
        properties.getUpload().setAccountQuotaFiles(2);
        properties.getUpload().setGenerationQuotaBytes(20);
        properties.getUpload().setGenerationQuotaFiles(3);
        properties.getUpload().setMinFreeBytes(100);
        properties.getUpload().setMinFreeRatio(0.20);

        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.h2.Driver");
        dataSource.setUrl("jdbc:h2:mem:demo-quota-" + UUID.randomUUID()
                + ";MODE=MariaDB;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=5000");
        jdbcTemplate = new JdbcTemplate(dataSource);
        transactionTemplate = new TransactionTemplate(new DataSourceTransactionManager(dataSource));
        jdbcTemplate.execute("""
                CREATE TABLE demo_seed_manifest (
                    id TINYINT PRIMARY KEY,
                    reset_at TIMESTAMP(6) NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE stored_files (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    created_at TIMESTAMP(6),
                    uploader_id BIGINT,
                    size BIGINT NOT NULL,
                    status VARCHAR(32)
                )
                """);
        jdbcTemplate.update(
                "INSERT INTO demo_seed_manifest(id, reset_at) VALUES (1, ?)",
                Timestamp.valueOf(RESET_AT)
        );
    }

    @Test
    @DisplayName("manifest reset_at 이전 canonical 파일은 제외하고 account byte 경계를 포함해 허용")
    void account_quota_is_rebuilt_from_current_generation_rows() {
        insertFile(RESET_AT.minusDays(1), 1L, 1_000);
        insertFile(RESET_AT, 1L, 6);
        DemoUploadQuotaGuard guard = guardWithDisk(1_000, 1_000);

        transactionTemplate.executeWithoutResult(ignored ->
                guard.assertUploadAllowed(1L, 4, STORAGE_PATH));

        assertThatThrownBy(() -> transactionTemplate.executeWithoutResult(ignored ->
                guard.assertUploadAllowed(1L, 5, STORAGE_PATH)))
                .isInstanceOf(BusinessException.class)
                .hasFieldOrPropertyWithValue(
                        "errorCode",
                        DemoErrorCode.DEMO_UPLOAD_QUOTA_EXCEEDED
                );
    }

    @Test
    @DisplayName("모든 상태와 계정을 합친 generation file/byte quota는 backend 객체 재생성 뒤에도 유지")
    void generation_quota_is_durable_across_guard_recreation() {
        insertFile(RESET_AT.plusSeconds(1), 1L, 6, "PENDING");
        insertFile(RESET_AT.plusSeconds(2), 2L, 6, "DELETE_PENDING");
        properties.getUpload().setGenerationQuotaBytes(12);

        DemoUploadQuotaGuard recreated = guardWithDisk(1_000, 1_000);

        assertThatThrownBy(() -> transactionTemplate.executeWithoutResult(ignored ->
                recreated.assertUploadAllowed(1L, 1, STORAGE_PATH)))
                .isInstanceOf(BusinessException.class)
                .hasFieldOrPropertyWithValue(
                        "errorCode",
                        DemoErrorCode.DEMO_UPLOAD_QUOTA_EXCEEDED
                );
    }

    @Test
    @DisplayName("manifest singleton row lock이 near-limit 동시 업로드를 직렬화")
    void concurrent_uploads_cannot_race_past_quota() throws Exception {
        properties.getUpload().setAccountQuotaFiles(16);
        properties.getUpload().setGenerationQuotaFiles(32);
        properties.getUpload().setGenerationQuotaBytes(10);
        DemoUploadQuotaGuard guard = guardWithDisk(1_000, 1_000);
        CountDownLatch start = new CountDownLatch(1);
        CountDownLatch done = new CountDownLatch(2);
        AtomicInteger accepted = new AtomicInteger();
        AtomicInteger rejected = new AtomicInteger();

        try (var executor = Executors.newFixedThreadPool(2)) {
            for (int i = 0; i < 2; i++) {
                executor.submit(() -> {
                    try {
                        start.await();
                        transactionTemplate.executeWithoutResult(ignored -> {
                            guard.assertUploadAllowed(1L, 6, STORAGE_PATH);
                            insertFile(RESET_AT.plusMinutes(1), 1L, 6);
                        });
                        accepted.incrementAndGet();
                    } catch (BusinessException quotaExceeded) {
                        if (quotaExceeded.getErrorCode() == DemoErrorCode.DEMO_UPLOAD_QUOTA_EXCEEDED) {
                            rejected.incrementAndGet();
                        }
                    } catch (InterruptedException interrupted) {
                        Thread.currentThread().interrupt();
                    } finally {
                        done.countDown();
                    }
                });
            }
            start.countDown();
            assertThat(done.await(5, TimeUnit.SECONDS)).isTrue();
        }

        assertThat(accepted).hasValue(1);
        assertThat(rejected).hasValue(1);
        assertThat(jdbcTemplate.queryForObject(
                "SELECT COALESCE(SUM(size), 0) FROM stored_files",
                Long.class
        )).isEqualTo(6L);
    }

    @Test
    @DisplayName("prospective write 후 max(고정 여유, 20%)를 정확히 남겨야 함")
    void disk_reserve_is_fail_closed_at_exact_boundary() {
        DemoUploadQuotaGuard exact = guardWithDisk(1_000, 210);
        exact.assertDiskReserve(STORAGE_PATH, 10);

        DemoUploadQuotaGuard shortByOne = guardWithDisk(1_000, 209);
        assertThatThrownBy(() -> shortByOne.assertDiskReserve(STORAGE_PATH, 10))
                .isInstanceOf(BusinessException.class)
                .hasFieldOrPropertyWithValue(
                        "errorCode",
                        DemoErrorCode.DEMO_STORAGE_UNAVAILABLE
                );
    }

    @Test
    @DisplayName("FileStore 조회 실패는 저장을 허용하지 않음")
    void disk_probe_failure_is_fail_closed() {
        DemoUploadQuotaGuard guard = new DemoUploadQuotaGuard(
                jdbcTemplate,
                properties,
                ignored -> {
                    throw new IOException("probe failed");
                }
        );

        assertThatThrownBy(() -> guard.assertDiskReserve(STORAGE_PATH, 1))
                .isInstanceOf(BusinessException.class)
                .hasFieldOrPropertyWithValue(
                        "errorCode",
                        DemoErrorCode.DEMO_STORAGE_UNAVAILABLE
                );
    }

    private DemoUploadQuotaGuard guardWithDisk(long totalBytes, long usableBytes) {
        return new DemoUploadQuotaGuard(
                jdbcTemplate,
                properties,
                ignored -> new DemoUploadQuotaGuard.DiskSpace(totalBytes, usableBytes)
        );
    }

    private void insertFile(LocalDateTime createdAt, long uploaderId, long size) {
        insertFile(createdAt, uploaderId, size, "CLAIMED");
    }

    private void insertFile(LocalDateTime createdAt, long uploaderId, long size, String status) {
        jdbcTemplate.update(
                "INSERT INTO stored_files(created_at, uploader_id, size, status) VALUES (?, ?, ?, ?)",
                Timestamp.valueOf(createdAt),
                uploaderId,
                size,
                status
        );
    }
}
