package io.github.ladium1.erp.global.demo;

import io.github.ladium1.erp.global.exception.BusinessException;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.transaction.support.TransactionTemplate;

import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class DemoExcelImportQuotaGuardTest {

    private static final LocalDateTime RESET_AT = LocalDateTime.of(2026, 8, 13, 9, 0);

    private DemoProperties properties;
    private JdbcTemplate jdbcTemplate;
    private TransactionTemplate transactionTemplate;
    private DemoExcelImportQuotaGuard guard;

    @BeforeEach
    void setUp() {
        properties = new DemoProperties();
        properties.setEnabled(true);
        properties.getUpload().setExcelAccountQuotaRows(3);
        properties.getUpload().setExcelGenerationQuotaRows(5);

        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.h2.Driver");
        dataSource.setUrl("jdbc:h2:mem:demo-excel-quota-" + UUID.randomUUID()
                + ";MODE=MariaDB;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=5000");
        jdbcTemplate = new JdbcTemplate(dataSource);
        transactionTemplate = new TransactionTemplate(new DataSourceTransactionManager(dataSource));
        jdbcTemplate.execute("CREATE TABLE demo_seed_manifest (id TINYINT PRIMARY KEY, reset_at TIMESTAMP(6) NOT NULL)");
        jdbcTemplate.execute("CREATE TABLE employees (id BIGINT PRIMARY KEY, login_id VARCHAR(64) NOT NULL UNIQUE)");
        jdbcTemplate.execute("""
                CREATE TABLE audit_logs (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    created_at TIMESTAMP(6), updated_at TIMESTAMP(6), action VARCHAR(255) NOT NULL,
                    actor_id BIGINT, actor_login_id VARCHAR(64) NOT NULL, ip_address VARCHAR(64),
                    menu_code VARCHAR(255) NOT NULL, target_id BIGINT, target_type VARCHAR(64), trace_id VARCHAR(8)
                )
                """);
        jdbcTemplate.update("INSERT INTO demo_seed_manifest(id, reset_at) VALUES (1, ?)", Timestamp.valueOf(RESET_AT));
        jdbcTemplate.update("INSERT INTO employees(id, login_id) VALUES (1, 'demo.manager'), (2, 'other.manager')");
        guard = new DemoExcelImportQuotaGuard(jdbcTemplate, properties);
        authenticate("demo.manager");
    }

    @AfterEach
    void clearAuthentication() {
        SecurityContextHolder.clearContext();
    }

    @Test
    @DisplayName("고객과 영업명부 import 행은 실제 생성 ID와 계정으로 합산되고 guard 재생성 뒤에도 유지")
    void account_quota_combines_both_import_kinds_durably() {
        transactionTemplate.executeWithoutResult(ignored -> guard.assertRowsAllowedAndRecord(
                DemoExcelImportQuotaGuard.ImportKind.CUSTOMER, List.of(101L, 102L)));

        DemoExcelImportQuotaGuard recreated = new DemoExcelImportQuotaGuard(jdbcTemplate, properties);
        transactionTemplate.executeWithoutResult(ignored -> recreated.assertRowsAllowedAndRecord(
                DemoExcelImportQuotaGuard.ImportKind.SALES_CONTACT, List.of(201L)));

        assertThatThrownBy(() -> transactionTemplate.executeWithoutResult(ignored ->
                recreated.assertRowsAllowedAndRecord(
                        DemoExcelImportQuotaGuard.ImportKind.CUSTOMER, List.of(103L))))
                .isInstanceOf(BusinessException.class)
                .hasFieldOrPropertyWithValue("errorCode", DemoErrorCode.DEMO_EXCEL_ROW_QUOTA_EXCEEDED);
        assertThat(jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM audit_logs WHERE target_type LIKE 'DEMO_%_EXCEL_IMPORT'", Long.class
        )).isEqualTo(3L);
    }

    @Test
    @DisplayName("reset 이전 감사 행은 제외하되 다른 계정까지 합친 generation quota를 적용")
    void generation_quota_uses_manifest_reset_boundary() {
        insertAudit(RESET_AT.minusSeconds(1), "demo.manager", 99L, "DEMO_CUSTOMER_EXCEL_IMPORT");
        authenticate("other.manager");
        transactionTemplate.executeWithoutResult(ignored -> guard.assertRowsAllowedAndRecord(
                DemoExcelImportQuotaGuard.ImportKind.CUSTOMER, List.of(1L, 2L, 3L)));
        authenticate("demo.manager");
        transactionTemplate.executeWithoutResult(ignored -> guard.assertRowsAllowedAndRecord(
                DemoExcelImportQuotaGuard.ImportKind.SALES_CONTACT, List.of(4L, 5L)));

        assertThatThrownBy(() -> transactionTemplate.executeWithoutResult(ignored ->
                guard.assertRowsAllowedAndRecord(
                        DemoExcelImportQuotaGuard.ImportKind.CUSTOMER, List.of(6L))))
                .isInstanceOf(BusinessException.class)
                .hasFieldOrPropertyWithValue("errorCode", DemoErrorCode.DEMO_EXCEL_ROW_QUOTA_EXCEEDED);
    }

    @Test
    @DisplayName("manifest lock이 near-limit 동시 import를 직렬화하고 초과 transaction을 rollback")
    void concurrent_imports_cannot_race_past_generation_quota() throws Exception {
        properties.getUpload().setExcelAccountQuotaRows(5);
        properties.getUpload().setExcelGenerationQuotaRows(5);
        CountDownLatch start = new CountDownLatch(1);
        CountDownLatch done = new CountDownLatch(2);
        AtomicInteger accepted = new AtomicInteger();
        AtomicInteger rejected = new AtomicInteger();

        try (var executor = Executors.newFixedThreadPool(2)) {
            for (int worker = 0; worker < 2; worker++) {
                int base = worker * 10;
                executor.submit(() -> {
                    try {
                        authenticate("demo.manager");
                        start.await();
                        transactionTemplate.executeWithoutResult(ignored -> guard.assertRowsAllowedAndRecord(
                                DemoExcelImportQuotaGuard.ImportKind.CUSTOMER,
                                List.of((long) base + 1, (long) base + 2, (long) base + 3)
                        ));
                        accepted.incrementAndGet();
                    } catch (BusinessException quotaExceeded) {
                        if (quotaExceeded.getErrorCode() == DemoErrorCode.DEMO_EXCEL_ROW_QUOTA_EXCEEDED) {
                            rejected.incrementAndGet();
                        }
                    } catch (InterruptedException interrupted) {
                        Thread.currentThread().interrupt();
                    } finally {
                        SecurityContextHolder.clearContext();
                        done.countDown();
                    }
                });
            }
            start.countDown();
            assertThat(done.await(5, TimeUnit.SECONDS)).isTrue();
        }

        assertThat(accepted).hasValue(1);
        assertThat(rejected).hasValue(1);
        assertThat(jdbcTemplate.queryForObject("SELECT COUNT(*) FROM audit_logs", Long.class)).isEqualTo(3L);
    }

    private void insertAudit(LocalDateTime createdAt, String actorLoginId, long targetId, String targetType) {
        jdbcTemplate.update("""
                        INSERT INTO audit_logs(created_at, updated_at, action, actor_id, actor_login_id,
                                               menu_code, target_id, target_type)
                        VALUES (?, ?, 'CREATE', 1, ?, 'CUSTOMERS', ?, ?)
                        """,
                Timestamp.valueOf(createdAt), Timestamp.valueOf(createdAt), actorLoginId, targetId, targetType);
    }

    private static void authenticate(String loginId) {
        SecurityContextHolder.getContext().setAuthentication(
                UsernamePasswordAuthenticationToken.authenticated(loginId, "n/a", List.of())
        );
    }
}
